[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Smart Data Center of SSF"
authors = [{name = "FusionSSF", email = "fusion@sjtu.edu.cn"}]
dynamic = ["version", "description"]
